[package]
name = "git-update"
license = "MIT"
version = "0.1.0"
authors = ["Geoff Johnson <geoff.jay@gmail.com>"]
edition = "2018"

[dependencies]
git2 = "0.13"
log = "0.4"
env_logger = "0.8.4"
regex = "1"
structopt = "0.3"
